# Uncommend the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s",
#  "iPad Air"
])

languages([
  'en-US'
])

# Where should the resulting screenshots be stored?
screenshots_path "/Users/bob/Projects/iPhone/Pomodoro/screenshots"

# clear_previous_screenshots # remove the '#'' to clear all previously generated screenshots before creating new ones

# JavaScript UIAutomation file
 js_file '/Users/bob/Projects/iPhone/Pomodoro/snapshot/snapshot.js'

# The name of the project's scheme
 scheme 'Pomodoro'

# Where is your project (or workspace)? Provide the full path here
 project_path '/Users/bob/Projects/iPhone/Pomodoro/Pomodoro/Pomodoro.xcodeproj'

# By default, the latest version should be used automatically. If you want to change it, do it here
 ios_version '8.3'

setup_for_device_change do |device, udid, language|
  puts "Running #{language} on #{device} with udid: #{udid}"
end

teardown_device do |language, device|
  puts "Finished with #{language} on #{device}"
  system("./cleanup.sh")
end